include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    prefer_final_fields: ignore
    file_names: ignore
    avoid_print: ignore
    use_build_context_synchronously: ignore
    no_leading_underscores_for_local_identifiers: ignore
