name: app_movil_coffe
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  charts_flutter: ^0.12.0
  curved_navigation_bar: ^1.0.6
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  http: ^1.2.2
  provider: ^6.1.2
  shared_preferences: ^2.3.1
  simple_animations: ^5.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 30


flutter:
  uses-material-design: true 
  assets:
    - assets/logo.png
    - assets/letra-morada.png
    - assets/letra-negra.png
    - assets/letras-blancas.png

